language: java
services:
- docker
script:
- mvn package
- docker run -v `pwd`/target:/smtp oracle/graalvm-ce bash -c "cd /smtp && gu install
  native-image && native-image -jar /smtp/*-with-dependencies.jar --no-fallback --static
  aws-smtp-relay"
- mvn package -P debian
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: yY0ewDlXFHL2zpZr8eJ+ox0yp/XBe9PJazE+KQMCZtOgVHnV3owC+SOeBz5cLW9S6i5puz46wjOhGcM3BMpBOCS/O7It5oidKBafckJa41idvgYNrGs7QbR7oa0K1DOEBRvNVFRvb9WNSCMDyOP2GReFdbZOjZpytRgiGho+kSqK49PB0W+E10ZM95p+DSZfTHPiuZ2LtD6sRBiI6sK4TXyzLHkCvyLD7Q0B2WgWRxxQxuf4k1ovGvdSrEHob7MU3y7/g3bJIc3q2V7O2U46Bj/or6yBz8qtqeXWcsiG9IBedjNLcRdUFhDwOy4YkqMBKstibCur6tqjKdUVH0O9M4bl0a7RdB2jgwYJIWvxLlkmaEbYl3NdRCD5jtfc7EmWu95nfiaK5RYOtBrCWD+FHkjEYtdMoPDeHHxL9rEYL83yL3h0CmdTbtCLsr0XVI1l2A0m5d75agJ59KTQDbIx2WKoQHo/hs1A57fpwJ8yjHtlZPXamuI1RB5fBLMz8fiUDJb2cOoqsYoRJwRLYcxJHTwb611P0qoCNoThKvOeNNEhmjkoNxm++8SZxFwuYDnl3Yqvg+u/p2AAFCOTgG5qo3WW/bEPr1TgB6RcsLOerydin9n10hay1EFiVol111Fr32KcIvbkJPw+JgWvp4tK+/xbQlDv2Sp8bjI8cjl/AXY=
  file_glob: true
  file:
  - target/aws-smtp-relay
  - target/aws-smtp-relay*.jar
  - target/aws-smtp-relay_*.deb
  on:
    repo: michaa76/aws-smtp-relay
    tags: true