language: java
services:
- docker
env:
  global:
  - IMAGE_NAME=michaa76/aws-smtp-relay
  - secure: X97qDkfK9lkcCd0ILcHD2NuhcUbk6PCfgnFEQjFa7TQkOoh6czDx5OGhqgkOTbt85lPf/lZRwpBskrFYurqc/aovjBf0MlY9znFL1axMkUB51yAkUXg0jLmIYFH5OOH9/GxwPVjqiAH7Vr4WKIvL/pKkarhHSutCAuM1PWaqtnYx1VBVtQFh1KigH+suCXFE0WgVPw6BDLeVo7ZXWbDkOr1sVKKdbVVuHAt7utebbFw1ThnOoPlsVdA6MU/B8MYhV0nTK4FPrvn3DB3rtLsI384YLqqLD8Z/UH0EtciAF+ochwWS8Blo07ekAMwTVXFad5Ov4NlZenJZT4cRu5AADMUAlra3Jso593TQZV6kwP/EozuqA3znDZwxkRdLafAj3gGGnQs10U2vaSSpMoiU6uvm+oM+LLD4d5Z4B9kRj2oBI92vYcDjJduby4YCQCmkhqtO2x6fQ0z+BssjedC4rZWbfxVf8tLFcSGZwG31DwrXM/CXo6IxB7znRrEcBOe23D8uOy5SDGLVrwvOFV4rAuYbAG/DCrxY4pGdy9bYOZhGttQ4BToN7n+30lXrGnj6K8NIIgzM8IpFBU9av0jWMib65Ifi/1WhCTRAMKSN/awEEH/n2P3YJcoeATbvHMin6JTRfD0Tx6MMw3giVIQya0AEj2Cz3BOjzr39xuJ6czU=
  - secure: 4R9VZDy6bdqGrds+GvpDA8HM+HeesoaHti/zTxGoNucvwY5mbXhu3AL/ln8RCjQ+zBdxfinBhaMCic5Hy7FikMOqlV+2QmD4gLFPRov4Hs/T6Ss8//DxXLGHEK7lAh5mnlr8lof71ivSFk8P94g5p9mfJ1XI/ONA0lTtj8ZBQloI3Dk+DHETKPbYT2NYJEVAkczDIiKeX/8CYMoSyvo/1P1HHipinV4vzEYIfVhINu0I2IJPN7W+YLX2zsShvRVmdBvFJsWMjGik7dr+tw07BQqmCwSF12Q5xOR20Te7S3dT1eQ30G8IM6CSuYVgDdwamCkncFbXpYIlBth+vGbiTdzipBh51otbi9a2WM5OPpoauGLTdVjJji0TD+FQSFye/R2hrsBSyhdGaQZZMGpvSFCsjdJqtuQnc75S29cOD5X14NPa6K+fJIwKl2Z/XmO/tewzBU61JbuKh+5HrojDRIwkh6+RWfP6QCuX3mSX9Q4C5Y4+WG7DqEAglFYSdafGsAtEJfqdP2RxcEEuASrEQTEUHfkwjV92qAxKIaDyFmrixnRPFyjddyfvw9XSgIrw+hJOvMkYQ85/OaYdAzYPWQW0hAa3iOjZuExHeyrbR1ytYYEEEv+5LAP8F4PCA8CT81SOnGjODEdOJzzUg5cWK4AJKBuk5BFqw+dkGDmkaq8=
script:
- mvn package
- docker run -v `pwd`/target:/smtp oracle/graalvm-ce bash -c "cd /smtp && gu install native-image && native-image -jar /smtp/*-with-dependencies.jar --no-fallback --static --initialize-at-build-time aws-smtp-relay"
- mvn package -P debian
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: YtS/Fc5DoKUS+fJnjH1S6Ft9Zh0cE/jQbytNNBsKVaT2sZNa0cnm5rnlwGjHSQhR6IXYVnCjB8fi+67CfpeegaKZvJxe9ImDrSe129L7LMk0/PbIv2e7fYzOKbfdqTT+hdBGWCelDgd7JKi6pf0fOKHptKpaXzUO2oCG3pCnRK7MgxvydGjK5ozqQGOe+DZM/wHhA3tTCJ+MevxTWjKdml49EmfCxMtyX0hfLaRReEu/AVNe+nLj4fOKOl+FT52pI7IIexbDoSTN5fGGsw6RSeZoUfpqoxcc1Srs9BLDe1OZhIAfolQxb0pH3WnMitGSSAj3gXmrjGQv8WXYkukUOG3aZBbUxS9airO1Tqd+Qk+b/DOlLwdB7ns/UZ5GgAsv7Dct0uE12L8DixWjBIPVQDAygLvSdp89Kh2BmI4a1Dv3phY/h9ttiv8uzMRQxA159oMglSSeAb5L428Ol190gv08wDiudPirPSsVRYgWF28m1eViMVu8WMS8jijBuu8CqAbnG0wnQhal2pd0F2u2WjV6ISwSj6EG9nkQAkZAv5NQtfFY+WEbGv10TWpvokQ/cyuLrwpqf5THYW9I9fA+uReBt5q4UoVlwlQEAoeBLHSCtzfszlTtx4PeuwjeN7cM/77YPYAUbGFJG0qkNJeJ/1eItXGqnYNV4PYJZZq78os=
  file_glob: true
  file:
  - target/aws-smtp-relay
  - target/aws-smtp-relay*.jar
  - target/aws-smtp-relay_*.deb
  on:
    repo: michaa76/aws-smtp-relay
    tags: true
- provider: script
  script: bash docker_push
  on:
    tags: true
