language: java
services:
  - docker
script:
  - mvn package
  - docker run -v `pwd`/target:/smtp oracle/graalvm-ce bash -c "cd /smtp && gu install native-image && native-image -jar /smtp/*-with-dependencies.jar --no-fallback --static aws-smtp-relay"
  - mvn package -P debian
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bfbd51b7e1414cdd6366f519ee75f50ea9fb23bc
  file_glob: true
  file:
    - target/aws-smtp-relay
    - target/aws-smtp-relay*.jar
    - target/aws-smtp-relay_*.deb
  on:
    repo: michaa76/aws-smtp-relay
    tags: true
